# Generated by Django 4.1.7 on 2023-02-24 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('CarId', models.AutoField(primary_key=True, serialize=False)),
                ('Car_Name', models.CharField(max_length=255)),
                ('Car_Brand', models.CharField(max_length=255)),
                ('Car_Discription', models.CharField(max_length=1000)),
                ('Car_Rent', models.IntegerField()),
                ('Car_Image', models.ImageField(upload_to='product_image')),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
