# Generated by Django 4.1.7 on 2023-04-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_cardetail_available_places'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetail',
            name='Available_places',
        ),
    ]
