# Generated by Django 4.1.7 on 2023-02-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booknow', '0002_alter_book_id_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AlterField(
            model_name='book',
            name='Id_Proof',
            field=models.ImageField(upload_to='id_image'),
        ),
    ]
