# Generated by Django 4.1.7 on 2023-02-27 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Booknow', '0004_alter_book_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_Account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
