# Generated by Django 4.1.7 on 2023-03-01 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_cardetail_car_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Booknow', '0006_book_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentstatus', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booknow.book')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.cardetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
