# Generated by Django 4.1.7 on 2023-03-01 04:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_cardetail_car_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Booknow', '0007_purchaseditems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchasedItems',
            new_name='BookedCar',
        ),
    ]
