# Generated by Django 4.1.7 on 2023-03-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booknow', '0010_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedcar',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
