# Generated by Django 4.1.7 on 2023-04-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booknow', '0011_bookedcar_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Phone_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
