# Generated by Django 4.1.7 on 2023-04-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booknow', '0012_book_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Phone_no',
            field=models.IntegerField(max_length=100000000000),
        ),
    ]
